[package]
name    = "font41"
version = "0.2.1"
edition = "2024"

[dependencies]
bitflags.workspace       = true
flate2.workspace         = true
fontdb                   = "0.24.0"
harfrust                 = "0.13.3"
icu_properties.workspace = true
log.workspace            = true
memmap2                  = "0.9.11"
png.workspace            = true
raqote                   = { version = "0.8.5", default-features = false }
read-fonts               = "0.43.3"
resvg                    = { version = "0.48.1", default-features = false }
smol_str.workspace       = true
